name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '❌ BREAKING CHANGES'
    labels:
      - 'breaking'
      - 'BREAKING'
  - title: '🚀 Features & Enhancements'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '📖 Documentation'
    labels:
      - 'doc'
      - 'docs'
      - 'documentation'
  - title: '📦 Dependency Updates'
    label: 'dependencies'
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: minor
autolabeler:
  - label: 'BREAKING'
    title:
      - '/breaking/i'
  - label: 'feature'
    title:
      - '/add/i'
  - label: 'enhancement'
    title:
      - '/improve/i'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'chore'
    title:
      - '/chore/i'
      - '/clean/i'
      - '/remove/i'
  - label: 'docs'
    title:
      - '/docs/i'
      - '/doc/i'
  - label: 'dependencies'
    title:
      - '/update/i'
      - '/upgrade/i'
      - '/rev/i'
template: |
  # What's Changed (Override)

  $CHANGES
