name: Test

on:
  workflow_dispatch:
    inputs:
      version:
        description: version
        required: true

jobs:
  # test:
  #   name: Deploying Version ${{ inputs.version }} to Development
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: development
  #     url: https://github.com/${{ github.repository }}/releases/tag/v${{ inputs.version }}
  #   steps:
  #     - name: Test
  #       shell: bash
  #       run: |
  #         echo "hello world"

  test-matrix:
    name: matrix
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://github.com/${{ github.repository }}/releases/tag/v${{ inputs.version }}
    strategy:
      matrix:
        include:
          - key: foo
          - key: bar
    steps:
      - name: Deploying [${{ matrix.key }}] - SHA [${{ github.sha }}]
        shell: bash
        run: |
          echo "hello ${{ matrix.key }}"
