name: Test

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Test
        shell: bash
        run: |
          echo "hello world"
