name: Test

on:
  push:
   branches:
     - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        shell: bash
        run: |
          echo "hello world"
