name: Test

on:
  workflow_dispatch:
    inputs:
      version:
        description: version
        required: true

jobs:
  # test:
  #   name: Deploying Version ${{ inputs.version }} to Development
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: development
  #     url: https://github.com/${{ github.repository }}/releases/tag/v${{ inputs.version }}
  #   steps:
  #     - name: Test
  #       shell: bash
  #       run: |
  #         echo "hello world"

  production-review:
    name: production-review
    runs-on: ubuntu-latest
    environment:
      name: dne # development
      url: https://github.com/${{ github.repository }}/releases/tag/v${{ inputs.version }}
    steps:
      - name: Deploying
        run: echo "Deploying ${{ inputs.version }}"

  test-matrix:
    name: matrix
    runs-on: ubuntu-latest
    needs: production-review
    strategy:
      matrix:
        include:
          - key: foo
            value: 1
          - key: bar
            value: 2
    steps:
      - name: Deploying [${{ matrix.key }}] - SHA [${{ github.sha }}]
        shell: bash
        run: |
          echo "hello ${{ matrix.key }} ${{ matrix.value }}"
